# Sample configuration file for the Condor pipeline conversion
# John Hoffman 2/28/2017

# This file is the input file for
#         ctbb_pipeline_convert.py

# Specify the Pipeline library that contains our study data
# This is the file that contains our .ctbb_plib lock file
library: \\skynet\\cvib\PechinTest2\emphysema\library

# Currently unsupported options
input_type: ['img']
output_type: ['hr2']
