# Sample configuration file for the Condor pipeline segmentation implementations
# John Hoffman 2/28/2017

# This file is the input file for
#         ctbb_pipeline_segment.py

# Specify the Pipeline library that contains our study data
# This is the file that contains our .ctbb_plib lock file
library: \\skynet\\cvib\PechinTest2\emphysema\library

# If desired, specify a "parent" segmentation
# This is the segmentation that will be inherited by a study
# This is useful if you want to segment on low-noise cases
# and apply to the same scan at high-noise configurations
parent_seg:
  dose: 100
  kernel: 1
  slice_thickness: []
