# Script to automatically configure paths.yml
# Do not use drive letters! Full paths of network shares only.

import platform

with open('paths.yml','w') as f:
    f.write("# This file is automatically generated. Do not edit.\n\n");

    # Specify location of other pipeline code
    # KLUDGE until we develop betting install infrastructure for "pypeline.py"
    if platform.system()=='Linux':
        f.write("pipeline_library: /home/john/Code/CTBangBang_Pipeline/src/\n")
    elif platform.system()=='Windows':
        f.write("pipeline_library: \\\ldap\ldaphome\jhoffman\CTBB_Pipeline\src\ \r\n")

    # Specify location of Condor public scripts
    # KLUDGE until we come up with something system independent
    f.write("segmentation_script: \\\ldap\ldaphome\jhoffman\pipeline_scripts\segment_lung_condor.py\n")
    f.write("submit_script: \\\skynet\cvib\PechinTest2\scripts\submit.py\n")
    f.write("automount_script: \\\skynet\cvib\PechinTest2\scripts\\auto_mount_conf.py\n")
    f.write("test_script: \\\ldap\ldaphome\jhoffman\pipeline_scripts\condor_test.py\n")
