# Script to automatically configure paths.yml
# Do not use drive letters! Full paths of network shares only.

import platform

with open('paths.yml','w') as f:
    f.write("# This file is automatically generated. Do not edit.\n\n");

    # Specify location of other pipeline code
    # KLUDGE until we develop betting install infrastructure for "pypeline.py"
    if platform.system()=='Linux':
        f.write("pipeline_library: /home/john/Code/CTBangBang_Pipeline/src/\n")
    elif platform.system()=='Windows':
        f.write("pipeline_library: \\\ldap\ldaphome\jhoffman\CTBB_Pipeline\src\ \r\n")

    # Condor public scripts
    # These scripts handle condor job submission however don't handle
    # individual tasks (such as file conversion or segmentation)    
    # KLUDGE until we come up with something system independent    
    f.write("submit_script: \\\skynet\cvib\PechinTest2\scripts\submit.py\n")
    f.write("automount_script: \\\skynet\cvib\PechinTest2\scripts\\auto_mount_conf.py\n")

    # Job-specific scripts
    # Handle a single task for the pipeline. These are the scripts that jobs call once
    # they have been submitted to Condor.  This might be conversion from .img to .hr2, segmenting
    # the lungs, running CAD, or running histogramming
    f.write("test_script: \\\skynet\cvib\PechinTest2\scripts\condor_test.py\n")
    f.write("segmentation_script: \\\skynet\cvib\PechinTest2\scripts\segment_hr2_file.py\n")
    f.write("conversion_script: \\\skynet\cvib\PechinTest2\scripts\convert_img_file.py\n")
    f.write("histogram_script: \\\skynet\cvib\PechinTest2\scripts\calculate_histogram.py\n")
    f.write("emphysema_score_script: \\\skynet\cvib\PechinTest2\scripts\score_emphysema.py\n")
    
    # QIA Library path
    # Specify location of QIA library
    f.write("qia_module: \\\skynet\cvib\PechinTest2\scripts\qia_pipeline\src\ \n")
