# Script to automatically configure paths.yml
with open('paths.yml','w') as f:
    f.write("# This file is automatically generated. Do not edit.\n\n");

    # specify location of other pipeline code
    # KLUDGE until we develop betting install infrastructure for "pypeline.py"
    f.write("pipeline_library: /home/john/Code/CTBangBang_Pipeline/src/\n")

    # Specify location of Condor public scripts
    # KLUDGE until we come up with something system independent
    f.write("segmentation_script: H:\pipeline_scripts\segment_lung_condor.py\n")
